environment:
  # This key is encrypted using secdev's appveyor private key,
  # dissected only on master builds (not PRs) and is used during
  # npcap OEM installation
  npcap_oem_key:
    secure: d120KTZBsVnzZ+pFPLPEOTOkyJxTVRjhbDJn9L+RYnM=
  # Python versions that will be tested
  # Note: it defines variables that can be used later
  matrix:
    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "64"
      TOXENV: "py27-windows"
      WINPCAP: "false"
    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7.x"
      PYTHON_ARCH: "64"
      TOXENV: "py37-windows"
      WINPCAP: "false"
    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7.x"
      PYTHON_ARCH: "64"
      TOXENV: "py37-windows"
      WINPCAP: "true"

# There is no build phase for Scapy
build: off

install:
  # Install the npcap, windump and wireshark suites
  - ps: .\.appveyor\InstallNpcap.ps1
  - ps: .\.appveyor\InstallWindump.ps1
  - choco install -y wireshark
  # Install Python modules
  - "%PYTHON%\\python -m pip install tox"
  - set PATH=%PYTHON%\\Scripts\\;%PATH%

# Compatibility run with Winpcap
# XXX Remove me when wireshark stops using it as default
for:
  -
    matrix:
      only:
        - WINPCAP: "true"
    install:
      # Install the winnpcap, windump and wireshark suites
      - choco install -y winpcap
      - choco install -y windump
      - choco install -y wireshark
      # Install Python modules
      - "%PYTHON%\\python -m pip install tox"

test_script:
  # Set environment variables
  - set PYTHONPATH=%APPVEYOR_BUILD_FOLDER%
  - set PATH=%APPVEYOR_BUILD_FOLDER%;C:\Program Files\Wireshark\;C:\Program Files\Windump\;%PATH%
  
  # Main unit tests
  - "%PYTHON%\\python -m tox"

after_test:
  # Install & run codecov
  - tox -e codecov
